network:
    version: 2
    renderer: NetworkManager

    ethernets:
        eth0:
            dhcp4: false
        eth1:
            dhcp4: true
            nameservers:
                addresses: [8.8.8.8]
    bridges:
        br-lan:
            addresses:
                - 192.168.1.1/24
            interfaces:
                - eth0

