#!/bin/bash -e

VERSION=1.0
BUILD_DIR=./build
IMAGE_DIR=${BUILD_DIR}/image
TARGET_ROOTFS_DIR=${BUILD_DIR}/binary
MOUNTPOINT=./rootfs

SYSTEM=$1
DISTRIBUTION=$2
ROOTFSIMAGE=$SYSTEM-$DISTRIBUTION-${VERSION}.img

echo Making rootfs!

if [ -e ${ROOTFSIMAGE} ]; then
	rm ${ROOTFSIMAGE}
fi
if [ -e ${MOUNTPOINT} ]; then
	rm -r ${MOUNTPOINT}
fi

# Create directories
mkdir ${MOUNTPOINT}
dd if=/dev/zero of=${ROOTFSIMAGE} bs=1M count=1024

finish() {
	sudo umount ${MOUNTPOINT} || true
	echo -e "\e[31m MAKE ROOTFS FAILED.\e[0m"
	exit -1
}

echo Format rootfs to ext4
mkfs.ext4 ${ROOTFSIMAGE}

echo Mount rootfs to ${MOUNTPOINT}
sudo mount  ${ROOTFSIMAGE} ${MOUNTPOINT}
trap finish ERR

echo Copy rootfs to ${MOUNTPOINT}
sudo cp -rfp ${TARGET_ROOTFS_DIR}/*  ${MOUNTPOINT}

echo Install packages to ${MOUNTPOINT}
[ -f "./script/install_package" ] && ./script/install_package ${MOUNTPOINT}

echo Umount rootfs
sudo umount ${MOUNTPOINT}

echo Rootfs Image: ${ROOTFSIMAGE}

e2fsck -p -f ${ROOTFSIMAGE}
resize2fs -M ${ROOTFSIMAGE}

#rm -rf ${MOUNTPOINT}
if [ ! -d ${IMAGE_DIR} ]; then
	mkdir ${IMAGE_DIR}
fi
mv ${ROOTFSIMAGE} ${IMAGE_DIR}
