#!/bin/sh

# (C) 2012-2016 Fathi Boudra <fathi.boudra@linaro.org>

# Create configuration for live-build.

# You need live-build package installed.

SYSTEM=debian
DISTRIBUTION=bookworm

set -e

echo "I: create $SYSTEM $DISTRIBUTION configuration"
export LB_BOOTSTRAP_INCLUDE="apt-transport-https gnupg"

echo $SYSTEM > ./.system
echo $DISTRIBUTION > ./.distribution

[ ! -d ./build ] && mkdir build
cd ./build

lb config \
 --mirror-bootstrap "https://mirrors.tuna.tsinghua.edu.cn/debian" \
 --mirror-chroot "https://mirrors.tuna.tsinghua.edu.cn/debian" \
 --mirror-chroot-security "https://mirrors.tuna.tsinghua.edu.cn/debian-security" \
 --mirror-binary "https://mirrors.tuna.tsinghua.edu.cn/debian" \
 --mirror-binary-security "https://mirrors.tuna.tsinghua.edu.cn/debian-security" \
 --apt-indices false \
 --apt-recommends false \
 --apt-secure false \
 --architectures arm64 \
 --archive-areas 'main contrib non-free' \
 --backports false \
 --binary-filesystem ext4 \
 --binary-images tar \
 --bootappend-live "hostname=admin username=admin" \
 --bootstrap-qemu-arch arm64 \
 --bootstrap-qemu-static /usr/bin/qemu-aarch64-static \
 --cache true \
 --chroot-filesystem none \
 --compression gzip \
 --debootstrap-options "--variant=minbase --include=apt-transport-https,gnupg" \
 --distribution $DISTRIBUTION \
 --gzip-options '-9 --rsyncable' \
 --iso-publisher 'Linaro; http://www.linaro.org/; linaro-dev@lists.linaro.org' \
 --iso-volume 'Linaro Bookworm $(date +%Y%m%d-%H:%M)' \
 --linux-flavours none \
 --linux-packages none \
 --mode $SYSTEM \
 --security true \
 --system systemd \
 --updates false

test -d ../custom && cp -rf ../custom/* config/

echo "I: done configure"
