#!/bin/sh

# (C) 2012-2016 Fathi Boudra <fathi.boudra@linaro.org>

# Create configuration for live-build.

# You need live-build package installed.

SYSTEM=ubuntu
DISTRIBUTION=jammy

set -e

echo "I: create $SYSTEM $DISTRIBUTION configuration"
export LB_BOOTSTRAP_INCLUDE="apt-transport-https gnupg"

echo $SYSTEM > ./.system
echo $DISTRIBUTION > ./.distribution

[ ! -d ./build ] && mkdir build
cd ./build

lb config \
 --mirror-bootstrap "https://ports.ubuntu.com/ubuntu-ports" \
 --mirror-chroot "https://ports.ubuntu.com/ubuntu-ports" \
 --mirror-chroot-security "https://ports.ubuntu.com/ubuntu-ports" \
 --mirror-binary "https://ports.ubuntu.com/ubuntu-ports" \
 --mirror-binary-security "https://ports.ubuntu.com/ubuntu-ports" \
 --apt-indices false \
 --apt-recommends false \
 --apt-secure false \
 --architectures arm64 \
 --archive-areas 'main restricted universe multiverse' \
 --backports false \
 --binary-filesystem ext4 \
 --binary-images tar \
 --bootappend-live "hostname=admin username=admin" \
 --bootstrap-qemu-arch arm64 \
 --bootstrap-qemu-static /usr/bin/qemu-aarch64-static \
 --cache true \
 --cache-packages true \
 --chroot-filesystem none \
 --compression gzip \
 --debootstrap-options "--variant=minbase --include=ca-certificates,gnupg" \
 --distribution $DISTRIBUTION \
 --gzip-options '-9 --rsyncable' \
 --iso-publisher 'Ubuntu; http://www.ubuntu.com/; ubuntu-users@lists.ubuntu.com' \
 --iso-volume 'Ubuntu Jammy $(date +%Y%m%d-%H:%M)' \
 --linux-flavours none \
 --linux-packages none \
 --mode $SYSTEM \
 --security true \
 --system systemd \
 --updates false	

test -d ../custom && cp -rf ../custom/* config/

echo "I: done configure"
